DATASET:
  NAME: "PLTNetMini"
  ROOT: "E:\\Others\\ensi_unlearning\\datasets\\plt_net_mini"

DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    BATCH_SIZE: 32
    SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 64
    SAMPLER: "SequentialSampler"

INPUT:
  SIZE: [224, 224]
  INTERPOLATION: "bilinear"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "CLIP-ViT-B/16"